BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "balena-rockchip"
BBFILE_PATTERN_balena-rockchip := "^${LAYERDIR}/"
BBFILE_PRIORITY_balena-rockchip = "1337"

LAYERSERIES_COMPAT_balena-rockchip = "wrynose"


# we need only the initramfs kernel in the rootfs so we remove the non-initramfs version
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "kernel-image"

# remove the extlinux package and only add it via IMAGE_INSTALL for the internal image
MACHINE_ESSENTIAL_EXTRA_RDEPENDS:remove = "u-boot-extlinux"

# the BSP sets this as fitImage but we don't use it because the flasher has problems when booting with an older u-boot and a fitImage kernel type
KERNEL_IMAGETYPE = "Image"
