name: Seeed reComputer RK3576 DevKit

on:
  pull_request:
    branches:
      - main
      - master
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  workflow_dispatch:

permissions:
  contents: read

jobs:
  yocto:
    name: Yocto
    uses: balena-os/balena-yocto-scripts/.github/workflows/yocto-build-deploy.yml@4b858287c2b8eb6ffb7bedb66908ddde47525605
    secrets: inherit
    with:
      machine: recomputer-rk3576-devkit
      test_matrix: >
        {
          "test_suite": ["os","cloud","hup"],
          "environment": ["balena-staging.com"],
          "runs_on": [["ubuntu-latest"]]
        }
